spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/tset;MODE=MYSQL
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
    show-sql: 'true'
    hibernate:
      ddl-auto: none